### ISSUE TITLE
Code highlighting does not work with a large padding

### ISSUE THREAD

**Issue by uralbash** [sophacles/vim-bundle-mako#5]
If too much padding the code highlighting does not work, see example:

![_068](https://cloud.githubusercontent.com/assets/619015/6460637/9d89bc78-c1ba-11e4-8d45-3bb16fa48538.png)

![_069](https://cloud.githubusercontent.com/assets/619015/6460642/aaccfc6a-c1ba-11e4-893c-caff88d8ec47.png)

**Comment by sophacles** [comment]
Woah.. that's really odd. I'll have to look into it. Thanks for the catch!

**Comment by timfeirg** [comment]
can't reproduce this on 86aa3c88f4bc8f32e659a94becb527a6e7094886, I added so much padding to one of my mako templates, the highlighting works fine, can you still reproduce? @uralbash

**Comment by uralbash** [comment]
@timfeirg I check and it works now
